apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
         - name: express-frontend
           image: adarshbhavimane/express-frontend:latest
           ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
